
export const HOME = '/'
export const SONG_SHEET = '/song-sheet'
export const SONG_SHEET_DETAIL = '/song-sheet-detail'
export const SINGER = '/singer'
export const SINGER_DETAIL = '/singer-detail'
export const PERSONAL = '/personal'
export const SETTING = '/setting'
export const PERSONAL_DATA = '/personal-data'
export const SIGN_IN = '/sign-in'
export const SIGN_UP = '/sign-up'
export const SEARCH = '/search'
export const LYRIC = '/lyric'
export const ERROR = '/404'
export const SIGN_OUT = 0
